// ACTIONS
export const INCREMENT = 'COUNTER_INCREMENT';
export const DECREMENT = 'COUNTER_DECREMENT';
export const SPINNER_UPDATE = 'SPINNER_UPDATE';

// OTHERS
export const SPINNER_MIN = 1;
export const SPINNER_MAX = 100;
